#!/bin/bash

echo "🧭 Testing Navigation Flow"
echo "========================="
echo ""
echo "1. Start the app: flutter run -d chrome"
echo "2. Go to Create Post screen"
echo "3. Fill in: 'Test post from script'"
echo "4. Add hashtag: '#test'"
echo "5. Click POST button"
echo "6. EXPECTED: Should return to Feed screen"
echo "7. Should see snackbar: 'Post created successfully!'"
echo "8. New post should be at TOP of feed"
echo ""
echo "🔧 If white screen appears:"
echo "   - Check console for errors"
echo "   - Press browser back button"
echo "   - Refresh the page"
echo ""
echo "📱 Quick test URL: http://localhost:XXXXX"
